src/Entity/Animal/Pet.php
<?php

/*
 * This file is part of the Monofony demo project.
 *
 * (c) Monofony
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Entity\Animal;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use App\Entity\IdentifiableTrait;
use App\Entity\Taxonomy\Taxon;
use App\Entity\Taxonomy\TaxonInterface;
use App\PetStates;
use App\Repository\PetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Sylius\Component\Resource\Annotation\SyliusCrudRoutes;
use Sylius\Component\Resource\Annotation\SyliusRoute;
use Sylius\Component\Resource\Model\ResourceInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Valid;

#[ORM\Entity(repositoryClass: PetRepository::class)]
#[SyliusCrudRoutes(alias: 'app.pet', path: '/admin/pets', section: 'backend', redirect: 'update', templates: 'backend/crud', grid: 'app_pet', except: ['index'], vars: [
    'all' => [
        'subheader' => 'app.ui.manage_your_pets',
        'templates' => [
            'form' => 'backend/pet/_form.html.twig',
        ],
    ],
])]
#[SyliusRoute(name: 'app_backend_pet_index', path: '/admin/pets/', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: 'backend/pet/index.html.twig', vars: ['subheader' => 'app.ui.manage_your_pets', 'icon' => 'cat'], section: 'backend', permission: true, grid: 'app_pet')]
#[SyliusRoute(name: 'app_backend_pet_per_taxon_index', path: '/admin/pets/taxon/{taxonId}', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: 'backend/pet/index.html.twig', vars: ['subheader' => 'app.ui.manage_your_pets', 'icon' => 'cat'], section: 'backend', permission: true, grid: 'app_pet')]
#[SyliusRoute(name: 'app_backend_partial_pet_latest', path: '/admin/_partial/pets/latest/{count}', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: '$template', repository: ['method' => 'findLatest', 'arguments' => ['!!int $count']])]
#[SyliusCrudRoutes(alias: 'app.pet', path: '/pets', identifier: 'slug', section: 'frontend', templates: 'frontend/pet', grid: 'app_frontend_pet', only: ['index', 'show'])]
#[SyliusRoute(name: 'app_frontend_pet_per_taxon_index', path: '/pets/taxon/{slug}', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: 'frontend/pet/index.html.twig', requirements: ['slug' => '.+'], grid: 'app_frontend_pet_per_taxon')]
#[SyliusRoute(name: 'app_frontend_pet_book', path: '/pets/{slug}/book', methods: ['POST'], controller: 'app.controller.pet::applyStateMachineTransitionAction', requirements: ['slug' => '.+'], redirect: ['route' => 'app_frontend_booking_confirmation', 'parameters' => ['slug' => 'resource.slug']], stateMachine: ['graph' => 'pet_booking', 'transition' => 'book'])]
#[SyliusRoute(name: 'app_frontend_partial_pet_latest', path: '/_partial/pets/latest/{count}', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: '$template', repository: ['method' => 'findLatest', 'arguments' => ['!!int $count']], requirements: ['template' => '[^?]+'])]
#[SyliusRoute(name: 'app_frontend_partial_pet_show', path: '/_partial/pets/{slug}', methods: ['GET'], controller: 'app.controller.pet::showAction', template: '$template', requirements: ['template' => '[^?]+', 'slug' => '[^?]+'])]
#[SyliusRoute(name: 'app_frontend_ajax_pet_index', path: '/ajax/pets', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: 'frontend/pet/index/_main.html.twig', requirements: ['slug' => '.+'], grid: 'app_frontend_pet')]
#[SyliusRoute(name: 'app_frontend_ajax_pet_per_taxon_index', path: '/ajax/pets/taxon/{slug}', methods: ['GET'], controller: 'app.controller.pet::indexAction', template: 'frontend/pet/index/_main.html.twig', requirements: ['slug' => '.+'], grid: 'app_frontend_pet_per_taxon')]
#[ApiResource(normalizationContext: ['groups' => ['pet:read', 'file:read']])]
#[Get]
#[GetCollection]
#[GetCollection(uriTemplate: '/taxa/{code}/pets', uriVariables: ['code' => new Link(toProperty: 'taxon', fromClass: Taxon::class)])]
class Pet implements ResourceInterface
{
    use IdentifiableTrait;

    #[ORM\Column(type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    #[ApiProperty(identifier: false)]
    protected ?int $id = null;

    #[ORM\Column(type: 'string')]
    #[NotBlank]
    #[Groups(groups: ['pet:read'])]
    private ?string $name = null;

    #[ORM\Column(type: 'string', unique: true)]
    #[Gedmo\Slug(fields: ['name'])]
    #[ApiProperty(identifier: true)]
    private ?string $slug = null;

    #[ORM\Column(type: 'string')]
    private string $status;

    #[ORM\Column(type: 'boolean')]
    private bool $enabled = false;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Groups(groups: ['pet:read'])]
    private ?string $description = null;

    #[ORM\Column(type: 'float', nullable: true)]
    #[Groups(groups: ['pet:read'])]
    private ?float $size = null;

    #[ORM\Column(type: 'string', nullable: true)]
    #[Groups(groups: ['pet:read'])]
    private ?string $sizeUnit = null;

    #[ORM\Column(type: 'string', nullable: true)]
    #[Groups(groups: ['pet:read'])]
    private ?string $mainColor = null;

    #[ORM\Column(type: 'string', nullable: true)]
    #[Groups(groups: ['pet:read'])]
    private ?string $sex = null;

    #[ORM\ManyToOne(targetEntity: Taxon::class)]
    #[NotBlank]
    #[Groups(groups: ['pet:read'])]
    private ?TaxonInterface $taxon = null;

    #[ORM\OneToMany(
        mappedBy: 'pet',
        targetEntity: PetImage::class,
        cascade: ['persist'],
        orphanRemoval: true,
    )]
    #[Valid]
    #[Groups(groups: ['pet:read'])]
    private Collection $images;

    public function __construct()
    {
        $this->status = PetStates::NEW;
        $this->images = new ArrayCollection();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    public function getSize(): ?float
    {
        return $this->size;
    }

    public function setSize(?float $size): void
    {
        $this->size = $size;
    }

    public function getSizeUnit(): ?string
    {
        return $this->sizeUnit;
    }

    public function setSizeUnit(?string $sizeUnit): void
    {
        $this->sizeUnit = $sizeUnit;
    }

    public function getMainColor(): ?string
    {
        return $this->mainColor;
    }

    public function setMainColor(?string $mainColor): void
    {
        $this->mainColor = $mainColor;
    }

    public function getTaxon(): ?TaxonInterface
    {
        return $this->taxon;
    }

    public function setTaxon(?TaxonInterface $taxon): void
    {
        $this->taxon = $taxon;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(?string $sex): void
    {
        $this->sex = $sex;
    }

    public function getImages(): ?Collection
    {
        return $this->images;
    }

    public function getFirstImage(): ?PetImage
    {
        return false !== $this->getImages()->first() ? $this->getImages()->first() : null;
    }

    public function hasImage(PetImage $image): bool
    {
        return $this->images->contains($image);
    }

    public function addImage(PetImage $image): void
    {
        if (!$this->hasImage($image)) {
            $this->images->add($image);
            $image->setPet($this);
        }
    }

    public function removeImage(PetImage $image): void
    {
        $this->images->removeElement($image);
        $image->setPet(null);
    }
}

src/Form/Type/Pet/PetImageType.php
<?php

/*
 * This file is part of the Monofony demo project.
 *
 * (c) Monofony
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Form\Type\Pet;

use App\Entity\Animal\PetImage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class PetImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('file', FileType::class, [
                'label' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver
            ->setDefaults([
                'data_class' => PetImage::class,
            ])
        ;
    }

    public function getBlockPrefix(): string
    {
        return 'app_pet_image';
    }
}

src/Form/Type/Pet/PetType.php
<?php

/*
 * This file is part of the Monofony demo project.
 *
 * (c) Monofony
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Form\Type\Pet;

use App\Colors;
use App\Entity\Animal\Pet;
use App\Entity\Taxonomy\Taxon;
use App\Sexes;
use App\SizeUnits;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'sylius.ui.name',
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'label' => 'sylius.ui.description',
            ])
            ->add('size', NumberType::class, [
                'required' => false,
                'label' => 'app.ui.size',
            ])
            ->add('sizeUnit', ChoiceType::class, [
                'required' => false,
                'label' => 'app.ui.size_unit',
                'placeholder' => '---',
                'choices' => SizeUnits::choices(),
            ])
            ->add('mainColor', ChoiceType::class, [
                'required' => false,
                'label' => 'app.ui.main_color',
                'placeholder' => '---',
                'choices' => Colors::choices(),
            ])
            ->add('taxon', EntityType::class, [
                'class' => Taxon::class,
                'placeholder' => '---',
                'choice_label' => 'code',
                'group_by' => 'parent',
            ])
            ->add('sex', ChoiceType::class, [
                'label' => 'app.ui.sex',
                'required' => false,
                'placeholder' => '---',
                'choices' => Sexes::choices(),
            ])
            ->add('images', CollectionType::class, [
                'label' => 'sylius.ui.images',
                'entry_type' => PetImageType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pet::class,
        ]);
    }

    public function getBlockPrefix(): string
    {
        return 'app_pet';
    }
}

templates/frontend/pet/show/_breadcrumb.html.twig
<nav aria-label="You are here:" role="navigation">
    <ul class="breadcrumbs">
        <li>
            <a href="{{ path('app_frontend_homepage') }}" class="section">{{ 'sylius.ui.home'|trans }}</a>
        </li>
        {% if pet.taxon is not null %}
            {% set taxon = pet.taxon %}
            {% set ancestors = taxon.ancestors|reverse %}

            {% for ancestor in ancestors %}
                <li>
                    <a href="{{ path('app_frontend_pet_per_taxon_index', {'slug': ancestor.slug}) }}" class="section">{{ ancestor.name }}</a>
                </li>
            {% endfor %}

            <li>
                <a href="{{ path('app_frontend_pet_per_taxon_index', {'slug': taxon.slug}) }}" class="section">{{ taxon.name }}</a>
            </li>
        {% endif %}
        <li>
            <span class="show-for-sr">Current: </span> {{ pet.name }}
        </li>
    </ul>
</nav>

templates/frontend/pet/show/_images.html.twig
{% import 'macro/image.html.twig' as images %}

{% if pet.firstImage %}
    {% set source_path = pet.firstImage.path %}
    {% set original_path = source_path|imagine_filter('app_frontend_pet_show') %}
    {% set path = source_path|imagine_filter(filter|default('app_frontend_pet_show')) %}
{% else %}
    {% set original_path = '//placehold.it/400x300' %}
    {% set path = original_path %}
{% endif %}

<nav class="orbit-bullets cell show-for-medium medium-1">
    {% for image in pet.images %}
        {% set path = vich_uploader_asset(image, 'file') %}
        <button class="thumbnail-item {{ loop.first ? 'is-active' : ''}}" data-slide="{{ loop.index - 1 }}">
            <div class="thumbnail-wrapper">
                {{ images.render(path, 'app_frontend_pet_show', pet.name) }}
            </div>
        </button>
    {% endfor %}
</nav>
<div class="orbit-wrapper cell auto">
    <div class="orbit-controls hide-for-medium">
        <button class="orbit-previous rotate-down"><span class="show-for-sr">Previoux pic</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
                <path fill="#ffffff" fill-rule="evenodd" d="M7.098 11.337l7.592-7.591a.938.938 0 011.326 0l.886.885a.938.938 0 01.001 1.324L10.886 12l6.017 6.045a.937.937 0 01-.002 1.324l-.885.886a.938.938 0 01-1.326 0l-7.592-7.592a.938.938 0 010-1.326z"/>
            </svg>
        </button>
        <button class="orbit-next rotate-up"><span class="show-for-sr">Next pic</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
                <path fill="#ffffff" fill-rule="evenodd" d="M16.902 12.663L9.31 20.254a.938.938 0 01-1.326 0l-.886-.885a.938.938 0 01-.001-1.324L13.114 12 7.097 5.955A.937.937 0 017.1 4.631l.885-.886a.938.938 0 011.326 0l7.592 7.592a.938.938 0 010 1.326z"/>
            </svg>
        </button>
        </div>
    <ul class="orbit-container">
        {% for image in pet.images %}
            {% set path = vich_uploader_asset(image, 'file') %}
            <li class="{{ loop.first ? 'is-active' : ''}} orbit-slide">
                <figure class="orbit-figure">
                    <div class="orbit-image-wrapper">
                        {% set class = "orbit-image" %}
                        {{ images.render(path, 'app_frontend_pet_show', pet.name, class) }}
                    </div>
                </figure>
            </li>
        {% endfor %}
    </ul>
</div>